module.exports = function(mongoose) {
    /* _id field automatically generated by the database */
    var UserSchema = mongoose.Schema(
        {
            "username": String,
            "email": String,
            "password": String,
            "joinedDate": {type: Date, default: Date.now()},
            "admin": {type: Boolean, default: false},
            // TODO: Figure out how to upload pictures
            "picture": String,
            "usersFollowing": [String],
            "groceryStoresFollowing": [String],
            "location": [String]
        },
        {   collection: users
        }
    );
    return UserSchema;
};