module.exports = function(mongoose) {
    /* _id field automatically generated by the database */
    var UserSchema = mongoose.Schema(
        {
            "username": String,
            "email": String,
            "password": String,
            "joinedDate": {type: Date, default: Date.now()},
            "admin": {type: Boolean, default: false},
            "picture": String,
            "usersFollowing": [String],
            "groceryStoresFollowing": [mongoose.Schema.Types.Mixed],
            "location": String
        },
        {   collection: "users"
        }
    );

    return UserSchema;
};